services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    container_name: wordpress
    environment:
      - WP_URL=${WP_URL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_SUPERUSER=${WP_SUPERUSER}
      - WP_SUPERUSER_PASSWORD=${WP_SUPERUSER_PASSWORD}
      - WP_SUPERUSER_EMAIL=${WP_SUPERUSER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always
    depends_on:
      - mariadb

  redis:
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress

  pure-ftp:
    build:
      context: ./requirements/pure-ftp
      dockerfile: Dockerfile
    container_name: pure-ftp
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
    
volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/28