version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_ADMIN: ${DB_ADMIN}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - backend
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./srcs/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./srcs/nginx/conf/ssl:/etc/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - backend
    
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

networks:
  backend:
    driver: bridge