services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_USER_PASSWORD=${DB_USER_PASSWORD}
        - DB_SUPERUSER=${DB_SUPERUSER}
        - DB_SUPERUSER_PASSWORD=${DB_SUPERUSER_PASSWORD}
    container_name: mariadb
    user: "1001"
    volumes:
      - database:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx_container
    user: "1002:1000"
    volumes:
      - wordpress_data:/var/www/html/wordpress:ro
      - ./requirements/nginx/conf/ssl:/etc/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress_container
    user: "1003:1000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_HOST=${DB_HOST}
    volumes:
      - wordpress_data:/var/www/html/wordpress:rw
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always
    depends_on:
      - mariadb
  ftp:
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    container_name: ftp_container
    user: "1004"
    # environment:
    #   FTP_USER: ${FTP_USER}
    #   FTP_PASSWORD: ${FTP_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html/wordpress:rw
      - ./requirements/ftp/conf/ssl:/etc/ssl:ro
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
    
volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  backend:
    name: backend
    driver: bridge