services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb_container
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_ADMIN: ${DB_ADMIN}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    user: mysql
    volumes:
      - database:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx_container
    env_file:
      - .env
    user: nginx-user
    volumes:
      - wordpress_data:/var/www/html/wordpress:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/ssl:/etc/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress_container
    env_file:
      - .env
    environment:
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_HOST: mariadb
    user: wp-user
    group_add:
      - webgroup
    volumes:
      - wordpress_data:/var/www/html/wordpress:rw
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always
    depends_on:
      - mariadb
  ftp:
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    container_name: ftp_container
    env_file:
      - .env
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    user: ftp-user
    volumes:
      - wordpress_data:/var/www/html/wordpress:rw
      - ./requirements/ftp/conf/vsftpd.conf:/etc/vsftpd/vsftpd.conf:ro
      - ./requirements/ftp/conf/ssl:/etc/ssl:ro
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
    
volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  backend:
    name: backend
    driver: bridge