#TODO capire se FTPD deve essere accessibile dalla porta 443 e da nginx

services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - USER_ID=${MARIADB_USER_UID}
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_logs:/var/log
    ports:
      - "3307:3306"
    networks:
      - backend
    restart: always
    init: true

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - USER_ID=${NGINX_USER_UID}
        - GROUP_ID=${WP_GROUP_ID}
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html/wordpress
      - adminer_data:/var/www/html/adminer
      - nginx_logs:/var/log
    ports:
      - "443:443"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
    init: true

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - USER_ID=${WP_USER_UID}
        - GROUP_ID=${WP_GROUP_ID}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    container_name: wordpress
    environment:
      - DB_HOST=${DB_HOST}
      - WP_URL=${WP_URL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_SUPERUSER=${WP_SUPERUSER}
      - WP_SUPERUSER_PASSWORD=${WP_SUPERUSER_PASSWORD}
      - WP_SUPERUSER_EMAIL=${WP_SUPERUSER_EMAIL}
    volumes:
      - wordpress_data:/var/www/html/wordpress
      - wordpress_logs:/var/log
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always
    depends_on:
      - mariadb
    init: true

  redis:
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
      args:
        - USER_ID=${REDIS_USER_UID}
    container_name: redis
    volumes:
      - redis_logs:/var/log
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
    init: true

  vsftpd:
    build:
      context: ./requirements/vsftpd
      dockerfile: Dockerfile
      args:
        - USER_ID=${FTP_USER_UID}
        - GROUP_ID=${WP_GROUP_ID}
    container_name: vsftpd
    volumes:
      - wordpress_data:/var/www/html/wordpress
      - vsftpd_logs:/var/log
    ports:
      - "21:21"
      - "20:20"
      - "21000-21010:21000-21010"
    networks:
      - backend
    restart: always
    depends_on:
      - wordpress
    init: true

  adminer:
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
      args:
        - USER_ID=${ADMINER_USER_UID}
    container_name: adminer
    volumes:
      - adminer_data:/var/www/html/adminer
      - adminer_logs:/var/log
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always
    depends_on:
      - mariadb
    init: true
  
  # portfolio:
  #   build:
  #     context: ./requirements/portfolio
  #     dockerfile: Dockerfile
  #     args:
  #       - USER_ID=${PORTFOLIO_USER_UID}
  #
  #   container_name: portfolio
  #   volumes:
  #     - wordpress_data:/var/www/html/wordpress
  #     - portfolio_logs:/var/log
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - backend
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   init: true
  
  # fluentd:
  #   build:
  #     context: ./requirements/fluentd
  #     dockerfile: Dockerfile
  #   container_name: fluentd
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #   networks:
  #     - backend
  #   restart: always
  #   init: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress
      o: bind
  adminer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/adminer
      o: bind
  mariadb_logs:
  nginx_logs:
  wordpress_logs:
  redis_logs:
  vsftpd_logs:
  adminer_logs:
  # portfolio_logs:

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/28
