CREATE DATABASE `${DB_NAME}`;
USE ${DB_NAME};
CREATE USER '${DB_USER}'@'wordpress.backend' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER 'wp-user'@'wordpress.backend';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON `${DB_NAME}`.* TO '${DB_USER}'@'wordpress.backend';

FLUSH PRIVILEGES;